dist: trusty
language: c
sudo: false
env:
  global:
  - LEIPT=1.74.4
  - TESS=3.05.01

install:
- wget http://www.leptonica.org/source/leptonica-$LEIPT.tar.gz
- tar xvf leptonica-$LEIPT.tar.gz
- mv leptonica-$LEIPT leiptonica
- wget https://github.com/tesseract-ocr/tesseract/archive/$TESS.tar.gz
- tar xvf $TESS.tar.gz
- mv tesseract-$TESS tesseract
- export TESSERACT_INSTALL=$HOME/.tesseract
- export TESSERACT_PKG=$TESSERACT_INSTALL/lib/pkgconfig
- export LD_LIBRARY_PATH=$TESSERACT_INSTALL/lib:$LD_LIBRARY_PATH
- export PKG_CONFIG_PATH=$TESSERACT_PKG:$PKG_CONFIG_PATH
- export LIBLEPT_HEADERSDIR="$TESSERACT_INSTALL/include"
- export LDFLAGS="-L$TESSERACT_INSTALL/lib"
- export CFLAGS="-I$TESSERACT_INSTALL/include"

script:
- cd leiptonica
- ./configure --prefix=$TESSERACT_INSTALL --disable-static CFLAGS="-O3"
- make
- make install
- cd ..
- cd tesseract
- ./autogen.sh
- ./configure --prefix=$TESSERACT_INSTALL --disable-static CFLAGS="-O3"
- make
- make install
- cd ..
- cd $TESSERACT_INSTALL/share/tessdata/
- wget https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.traineddata
- cd $HOME
- tar cvfJ tesseract.tar.xz .tesseract
- ls -lah tesseract.tar.xz

deploy:
  provider: releases
  api_key:
    secure: UD+4avG9FX4Lqmn39su8WwYetdoLV7rS7sDyEqvGQ5N6Tclst2FfXqz3J8AUE7j7OPKsB8xPhtOusjIkSofDug5WqRcQ8VdoH8rfJPdoVW03rFMLuGcLn+2pYIoDKfW0gvv1hmKjDyV5+fhN9UFLPp8tDyd0aD1jGBOA2OQNrN+Tz2FdLvkSutBrCG6CP3ytL8/V7hCAYybQxs0phZFowgGhn/NpOlj1KZ6PFRKngnAxkLR92MJsSmNxz9Hs16f7rG/hiFJPrNzV+MBb6FZuLRJJT84137bt06v5ajNUgAZfukYaN2n/QPn04OVRNxDAC3KeUyiBtHSPncO7xfSR6zQydjgwUZvH9K2RHxXY1rvT6b6F50XPUDaOtPoIKTWCFkWbvkQamNiFrNBu9+4OicMFuJkI0dZ2Ubs6F3LvU5sJeQa2YUdR0NttWFH5U+J6nTpVSLS1aXbUpVSniU83yGV+9AMBTTOmbsmdxo2TCMsWYu4Ni7+z2W/CqZq8Ls5TQx89WoFl/s5Mfbs9WwNJa2nS44bKCYZ5QQzRU7OKeutRDQ6ObtQjVlgXM+UQG//9qRb1BeDcopb336mg2UcToTaQtkdLmsVbIKiIRwmHGYS4LRgo5qFxNpubBl2VlFWUWcziD8J4x9cFVF3/wfxxwd2S9cIzWjzejhhH9qeGcZQ=
  file: tesseract.tar.xz
  on:
    repo: nijel/tesseract-ocr-build
    tags: true
  skip-cleanup: yes
